[config]

[templates.alacritty]
input_path = 'colors.toml'
output_path = '~/.config/alacritty/colors.toml'

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.eww]
input_path = 'colors-eww.scss'
output_path = '~/.config/eww/colors.scss'
