[colors.primary]
background = '#101417'
foreground = '#dfe3e7'
 
[colors.cursor]
text = '#dfe3e7'
cursor = '#c1c7ce' 
 
[colors.vi_mode_cursor]
text = '#101417'
cursor = '#92cef5' 
 
[colors.search.matches]
foreground = '#41484d' 
background = '#ccc1e9' 
 
[colors.search.focused_match]
foreground = '#41484d' 
background = '#92cef5' 
 
[colors.footer_bar]
foreground = '#41484d' 
background = '#dfe3e7' 
 
[colors.hints.start]
foreground = '#41484d' 
background = '#b6c9d8' 
 
[colors.hints.end]
foreground = '#41484d' 
background = '#b6c9d8' 
 
[colors.selection]
text = '#101417'
background = '#92cef5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#92cef5' 
yellow = '#216487' 
blue = '#92cef5' 
magenta = '#ccc1e9' 
cyan = '#b6c9d8' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
